Repository wecode-bootcamp-korea/16-2nd-bestgo-frontend, pull requests merged in 2021-02, with the labels that each got.

#3 [16기 김기열] Login validation 기능 완료 & Social Kakao Login 추가 & 리뷰 반영
  package-lock.json
  package.json
  public/index.html
  src/Pages/Login/Components/Button/Buttons.js
  src/Pages/Login/Components/Button/icon-login-facebook-btn.svg
  src/Pages/Login/Components/Button/icon-login-kakaotalk-btn.svg
  src/Pages/Login/Components/Card/Card.js
  src/Pages/Login/Components/Input/EmailPasswordInput.js
  src/Pages/Login/Components/Social/KakaoSocialLogin.js
  src/Pages/Login/Login.js
  src/Pages/Main/Main.js
  src/Pages/Signup/Signup.js
  src/Routes.js
  src/config.js
Labels: Status: Accepted

#6 [16기 박영호] BestGo-Frontend "Modify: 리뷰반영"
  public/Data/userData.json
  public/Images/test.png
  src/Pages/RequestPage/Component/RequsetList.js
  src/Pages/RequestPage/RequestPage.js
  src/Routes.js
Labels: Status: 리뷰 요청

#7 [16기 박영호] BestGo-Frontend "Modify: 컨플릭트 오류해결"
  package-lock.json
  package.json
  public/Data/Introduction.json
  src/Components/Footer/Component/Data.js
  src/Components/Footer/Component/FooterCont.js
  src/Components/Footer/Component/FooterInfo.js
  src/Components/Footer/Component/IconList.js
  src/Components/Footer/Component/StoreBtn.js
  src/Components/Footer/Component/Usecontent.js
  src/Components/Footer/Footer.js
  src/Routes.js
  src/StyledReset.js
  src/Styles/GlobalStyle.js
  src/Styles/Reset.scss
  src/index.js
Labels: Status: 리뷰 요청, Status: 컨플릭트 해결 요청

#4 [16기 유호익] mainpage layout 과 기능구현 완료
  public/Data/category.json
  public/Data/sevicelist.json
  public/Images/css.png
  public/Images/git.png
  public/Images/html.png
  public/Images/js.png
  public/Images/python.png
  public/Images/react.png
  public/Images/sass.png
  public/Images/snake.png
  public/index.html
  src/Pages/Main/Category.js
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/Pages/Main/Modal/Modal.js
  src/Pages/Main/Service.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#12 [16기 박영호] BestGo-Frontend "Modify: 견적서 보내기 페이지 견적요청 및 레이아웃구현"
  public/Data/user.json
  public/Data/userData.json
  src/Components/Footer/Component/FooterInfo.js
  src/Pages/RequestDetail/Components/Postestimate.js
  src/Pages/RequestDetail/Components/UserList.js
  src/Pages/RequestDetail/RequestDetail.js
  src/Pages/RequestPage/Component/RequsetList.js
  src/Pages/RequestPage/RequestPage.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#10 [16기 김기열] Signup 레이아웃 및 Validation 완료
  public/index.html
  src/Pages/Login/Components/Input/EmailPasswordInput.js
  src/Pages/Signup/Components/Buttons.js
  src/Pages/Signup/Signup.js
  src/Pages/Signup/data/VelidationMsg.js
  src/Routes.js
  src/config.js
  src/index.js
Labels: Status: 리뷰 요청

#14 [16기 김기열] Feature/login 로그인 최종 수정
  src/Pages/Login/Components/Button/Buttons.js
  src/Pages/Login/Components/Social/KakaoSocialLogin.js
  src/Pages/Login/Login.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#8 [16기 김기열] FindPassword 최종 수정 완료
  src/Pages/FindPassword/FindPassword.js
  src/Pages/FindPassword/Reset.js
  src/Pages/FindPassword/Send.js
  src/Pages/FindPassword/data/VelidationMsg.js
  src/Pages/FindPassword/mail.svg
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#13 [16기 박영호] BestGo-Frontend "Modify: 컨플릭트 오류해결"
  public/Images/star.png
  public/Images/starblack.png
  src/Pages/SearchDetail/Components/GosuInfo.js
  src/Pages/SearchDetail/Data/Data.js
  src/Pages/SearchDetail/SearchDetail.js
  src/Routes.js
Labels: Status: Accepted

#16 [16기 박영호] BestGo-Frontend "Add: 고수찾기 레이아웃 구현"
  public/Data/SearchData.json
  src/Pages/RequestDetail/Components/UserList.js
  src/Pages/Search/Components/FilterBtn.js
  src/Pages/Search/Components/GosuList.js
  src/Pages/Search/Components/PageBtn.js
  src/Pages/Search/Data/Data.js
  src/Pages/Search/Search.js
  src/Routes.js
  src/config.js
  src/index.js
Labels: Status: Accepted

#1 [16기 박영호] BestGo-Frontend "Modify: 리뷰 내용 반영"
  package-lock.json
  package.json
  public/Data/estimateData.json
  public/Data/serviceList.json
  src/Components/FetchData.js
  src/Pages/Estimate/Component/SendEstimate.js
  src/Pages/Estimate/Component/ServiceList.js
  src/Pages/Estimate/Estimate.js
  src/Pages/Search/Components/GosuList.js
  src/Pages/SearchDetail/Components/GosuInfo.js
  src/Pages/SearchDetail/SearchDetail.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#15 [16기 유호익]: requestpage 레이아웃 및 기능 구현
  public/Data/Questions.json
  public/Data/Regions.json
  public/Data/Reviews.json
  public/Data/ServiceDetail.json
  src/Pages/Request/Aside.js
  src/Pages/Request/Form/Form.js
  src/Pages/Request/Request.js
  src/Pages/Request/Request.scss
  src/Pages/Request/star.png
  src/Pages/Request/starblack.png
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청, Status: 컨플릭트 해결 요청

#9 [16기 김기열] Navbar 레이아웃 완료
  package-lock.json
  package.json
  public/index.html
  src/Components/Navbar/CustomerNavbar.js
  src/Components/Navbar/ExpertNavbar.js
  src/Components/Navbar/MainNavbarLayout.js
  src/Components/Navbar/Navbar.js
  src/Components/Navbar/NavbarMenu/NavbarMenu.js
  src/Pages/Login/Login.js
  src/Pages/Signup/Signup.js
  src/Routes.js
  src/images/BestgoLogo.png
  src/images/MagnifyingGlass.svg
  src/images/bell.svg
  src/images/profile.svg
Labels: Status: 리뷰 요청

#17 [16기 김기열] feature/login 경로 수정
  src/Pages/Login/Components/Social/KakaoSocialLogin.js
Labels: Status: 리뷰 요청

#11 [16기 김기열]BestSignUp BestRegions 카카오 지역 검색 API 추가
  package-lock.json
  package.json
  public/Data/best.json
  src/Pages/Best/Best.js
  src/Pages/Best/Components/BestRegions.js
  src/Pages/Best/Components/BestSignup.js
  src/Pages/Best/Components/Frame/Frame.js
  src/Pages/FindPassword/FindPassword.js
  src/Pages/FindPassword/Reset.js
  src/Pages/FindPassword/Send.js
  src/Pages/Signup/Signup.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청
